version: "3.7"
services:
  database:
    image: mysql:latest
    container_name: phincon-database
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - MySQL:/var/lib/mysql
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        APP_PORT: ${APP_PORT}
    container_name: phincon-backend
    restart: unless-stopped
    volumes:
      - '.:/app'
    ports:
      - '4000:${APP_PORT}'
    depends_on:
      - database
  

volumes:
  MySQL:

